import RelativeConicArcs.Gates.ClebschRigidityTrust

/-!
# Axiom audit for the Clebsch rigidity boundary

This audit prints the axioms of the terminals exported with the rigidity
boundary for the Clebsch hexagon code: the coding dictionary, the
decoding synthesis, the rigidity spine and its bridge to the code, the chord
defect, the order-nine Sylvester configuration, and the specialized six-arc
statements attributed to the literature.
-/

#print axioms RelativeConicArcs.ClebschChordDefect.chordDefect_identity_of_moments
#print axioms RelativeConicArcs.ClebschChordDefect.clebsch_uncovered_formula
#print axioms RelativeConicArcs.ClebschChordDefect.orders_of_clebsch_uncovered_conic_card
#print axioms RelativeConicArcs.ClebschDye.deepHoleLocus_rigidifies_witnessCode
#print axioms RelativeConicArcs.ClebschDye.isClebschHexagon_of_uncovered_subset_conic
#print axioms RelativeConicArcs.ClebschDye.isClebschHexagon_of_uncovered_subset_planeConic
#print axioms RelativeConicArcs.ClebschDye.sixArc_cards_of_uncovered_subset_conic
#print axioms RelativeConicArcs.ClebschDye.sixArc_twelve_le_uncovered_card
#print axioms RelativeConicArcs.ClebschDye.sixArc_uncovered_add_brianchon_card
#print axioms RelativeConicArcs.ClebschDye.sixArc_uncovered_card_le_twelve_of_subset_planeQuadraticLocus
#print axioms RelativeConicArcs.Examples.Q11Coding.ambiguity_strata_counts
#print axioms RelativeConicArcs.Examples.Q11Coding.ambiguity_strata_sound
#print axioms RelativeConicArcs.Examples.Q11Coding.brianchonDirectionIndices_eq_indexThree
#print axioms RelativeConicArcs.Examples.Q11Coding.brianchon_decoder_matching_dictionary
#print axioms RelativeConicArcs.Examples.Q11Coding.brianchon_weightTwo_leaderSupports
#print axioms RelativeConicArcs.Examples.Q11Coding.distanceThree_leaderSupports_eq_chiralitySheets
#print axioms RelativeConicArcs.Examples.Q11Coding.projective_distanceThreeDirections_eq_standardConic
#print axioms RelativeConicArcs.Examples.Q11Coding.supportChirality_generatorOrbits_and_exchange
#print axioms RelativeConicArcs.Examples.Q11Coding.totalSyndromeDistance_exact
#print axioms RelativeConicArcs.Examples.Q11Coding.witness_code_coveringRadius_three
#print axioms RelativeConicArcs.Examples.Q11Coding.witness_mds_columns
#print axioms RelativeConicArcs.OddSixArcPrismExtraction.sixArc_uncoveredOnLine_card_le_order_sub_five
#print axioms RelativeConicArcs.Q9Sylvester.distanceTwo_clique_number_five
#print axioms RelativeConicArcs.SmallKGeometricBridge.fiveArc_not_conic_card
#print axioms RelativeConicArcs.SmallKGeometricBridge.fourArc_conic_card_order
#print axioms RelativeConicArcs.SmallKGeometricBridge.fourArc_uncovered_card
#print axioms RelativeConicArcs.SmallKGeometricBridge.sevenArc_primePower_conic_card_spectra
#print axioms RelativeConicArcs.SupportOrientationCommutant.adjoinGolden_integralPoints_eq_ZsqrtFive
#print axioms RelativeConicArcs.SupportOrientationCommutant.oddLattice_integralCommutant_eq_ZsqrtFive
#print axioms RelativeConicArcs.SupportOrientationCommutant.oddModule_rationalCommutant_eq_adjoinGoldenOperator
#print axioms RelativeConicArcs.SupportOrientationCover.antipodalQuotient_fiber_card_two
#print axioms RelativeConicArcs.SupportOrientationCover.fiveOrbital_one_mem_each_other_fiber
#print axioms RelativeConicArcs.SupportOrientationCover.fiveOrbitals_selfPaired
#print axioms RelativeConicArcs.SupportOrientationDeterminant.det_signedOrbital_add_diagonal
#print axioms RelativeConicArcs.SupportOrientationDeterminant.determinantPencil_oddPart_eq_supportCubic
#print axioms RelativeConicArcs.SupportOrientationHolonomy.fourPoint_twoGraph_identity
#print axioms RelativeConicArcs.SupportOrientationHolonomy.pairBalance_iff_sq_five
#print axioms RelativeConicArcs.SupportOrientationHolonomy.supportCubic_translation_invariant
#print axioms RelativeConicArcs.SupportOrientationHolonomy.supportSign_eq_triangleProduct
#print axioms RelativeConicArcs.SupportOrientationNodes.derivative_crossGoldenDeterminantLine_eval
#print axioms RelativeConicArcs.SupportOrientationNodes.singularPoints_crossGoldenDeterminant_eq_axisClasses
#print axioms RelativeConicArcs.SupportOrientationNodes.supportCubic_framePoints_ordinaryNodes
#print axioms RelativeConicArcs.SupportOrientationNodes.supportCubic_singularLocus_eq_frame
#print axioms RelativeConicArcs.SupportOrientationPentagon.orbitalDifference_sq_eq_ten_one_sub_deck
#print axioms RelativeConicArcs.SupportOrientationPentagon.signedOrbitalMatrix_sq
#print axioms RelativeConicArcs.SupportOrientationSymmetry.mem_orientedSupportCubicStabilizer_iff
#print axioms RelativeConicArcs.SupportOrientationSymmetry.mem_supportCubicProjectiveStabilizer_iff_cubicLine
#print axioms RelativeConicArcs.SupportOrientationSymmetry.orientedSupportCubic_index_two
#print axioms RelativeConicArcs.SupportOrientationSymmetry.orientedSupportCubic_stabilizer_equiv_A5
#print axioms RelativeConicArcs.SupportOrientationSymmetry.supportCubic_projectiveStabilizer_equiv_S5
#print axioms RelativeConicArcs.SupportOrientationTraceDual.det_crossGoldenBlock_eq_neg_supportCubic
