import RelativeConicArcs.SupportOrientationSpine

/-!
# Axiom audit for the golden orientation of the Clebsch support cubic

This audit prints the axioms of the orientation terminals exported with the
golden orientation boundary of the Clebsch support cubic: the antipodal cover
and its self-paired orbitals, the signed orbital square identities, the
triangle holonomy and two-graph identities, the determinant pencil, the
cross-golden trace dual, the singular locus and ordinary-node type of the
determinantal cubic, the `S₅` and `A₅` stabilizer boundary, and the rational
and integral commutants.
-/

#print axioms RelativeConicArcs.SupportOrientationCommutant.adjoinGolden_integralPoints_eq_ZsqrtFive
#print axioms RelativeConicArcs.SupportOrientationCommutant.oddLattice_integralCommutant_eq_ZsqrtFive
#print axioms RelativeConicArcs.SupportOrientationCommutant.oddModule_rationalCommutant_eq_adjoinGoldenOperator
#print axioms RelativeConicArcs.SupportOrientationCover.antipodalQuotient_fiber_card_two
#print axioms RelativeConicArcs.SupportOrientationCover.fiveOrbital_one_mem_each_other_fiber
#print axioms RelativeConicArcs.SupportOrientationCover.fiveOrbitals_selfPaired
#print axioms RelativeConicArcs.SupportOrientationDeterminant.det_signedOrbital_add_diagonal
#print axioms RelativeConicArcs.SupportOrientationDeterminant.determinantPencil_oddPart_eq_supportCubic
#print axioms RelativeConicArcs.SupportOrientationHolonomy.fourPoint_twoGraph_identity
#print axioms RelativeConicArcs.SupportOrientationHolonomy.pairBalance_iff_sq_five
#print axioms RelativeConicArcs.SupportOrientationHolonomy.supportCubic_translation_invariant
#print axioms RelativeConicArcs.SupportOrientationHolonomy.supportSign_eq_triangleProduct
#print axioms RelativeConicArcs.SupportOrientationNodes.derivative_crossGoldenDeterminantLine_eval
#print axioms RelativeConicArcs.SupportOrientationNodes.singularPoints_crossGoldenDeterminant_eq_axisClasses
#print axioms RelativeConicArcs.SupportOrientationNodes.supportCubic_framePoints_ordinaryNodes
#print axioms RelativeConicArcs.SupportOrientationNodes.supportCubic_singularLocus_eq_frame
#print axioms RelativeConicArcs.SupportOrientationPentagon.orbitalDifference_sq_eq_ten_one_sub_deck
#print axioms RelativeConicArcs.SupportOrientationPentagon.signedOrbitalMatrix_sq
#print axioms RelativeConicArcs.SupportOrientationSymmetry.mem_orientedSupportCubicStabilizer_iff
#print axioms RelativeConicArcs.SupportOrientationSymmetry.mem_supportCubicProjectiveStabilizer_iff_cubicLine
#print axioms RelativeConicArcs.SupportOrientationSymmetry.orientedSupportCubic_index_two
#print axioms RelativeConicArcs.SupportOrientationSymmetry.orientedSupportCubic_stabilizer_equiv_A5
#print axioms RelativeConicArcs.SupportOrientationSymmetry.supportCubic_projectiveStabilizer_equiv_S5
#print axioms RelativeConicArcs.SupportOrientationTraceDual.det_crossGoldenBlock_eq_neg_supportCubic
