import RelativeConicArcs.Gates.MDSCSSTransversalGeometry

/-!
# Axiom audit for diagonal isoduality and transversal Clifford groups of MDS--CSS codes

This audit prints the axioms of every terminal exported with the diagonal
isoduality boundary: the six-arc, code, state, and absolutely-maximally-entangled
dictionary, the stabilizer dictionary and character realization, the diagonal
multiplier line and nullity test, the exact fixed-party carrier dichotomies
with their generalized Reed--Solomon and order-16464 instances, the encoder
conversions and equal-phase rigidity imported from the companion paper, the
coset and syndrome geometry, the admitted-pencil quotient and its
classifications, the Frobenius-sector divisors, the marginal-moment separator,
the fixed-party logical phase, the four-copy separator, the transport divisor,
and the party-extension splitting consequences.
-/

#print axioms GroupExtension.Splitting.semidirectProductEquiv
#print axioms GroupExtension.factorSet_change
#print axioms GroupExtension.factorSet_trivializable_iff_splitting
#print axioms RelativeConicArcs.AMELU.GenericDiagonalDuality.diagonalMultiplierBilinForm_eq_zero
#print axioms RelativeConicArcs.AMELU.TransportCycleCoverInputs.axial_det_factor
#print axioms RelativeConicArcs.AMELU.TransportCycleCoverInputs.negativeSigned_det_factor
#print axioms RelativeConicArcs.AMELU.TransportCycleCoverInputs.positiveSigned_det_factor
#print axioms RelativeConicArcs.AMELU.TransportOrbitGeometryInputs.card_axial_union_negative
#print axioms RelativeConicArcs.AMELU.TransportOrbitGeometryInputs.card_axial_union_positive
#print axioms RelativeConicArcs.AMELU.TransportRankBridgeInputs.matchingRank_eq_twentyOne_of_transportRank_eq_nine
#print axioms RelativeConicArcs.AMELU.TransportRankBridgeInputs.matchingRank_eq_twenty_of_transportRank_eq_eight
#print axioms RelativeConicArcs.AMELU.admitted_nonGRS_map_iff
#print axioms RelativeConicArcs.AMELU.admitted_nonGRS_pencil_classified_by_z
#print axioms RelativeConicArcs.AMELU.affineSpecialLinearOrder_seven
#print axioms RelativeConicArcs.AMELU.axialCyclePolynomial_factor
#print axioms RelativeConicArcs.AMELU.card_marginalStars
#print axioms RelativeConicArcs.AMELU.card_marginalTriples
#print axioms RelativeConicArcs.AMELU.card_perfectMatchings
#print axioms RelativeConicArcs.AMELU.contractionMatchingRank_normalizeContractionPattern
#print axioms RelativeConicArcs.AMELU.contractionRankOrbitSum_permuteContractionPattern
#print axioms RelativeConicArcs.AMELU.cssLabelSpace_isPauliLagrangian
#print axioms RelativeConicArcs.AMELU.diagonalDualityMultiplierSpace_finrank_eq_zero_or_one
#print axioms RelativeConicArcs.AMELU.diagonalDualityNullity_fixedPartyProjectiveTransversal_dichotomy
#print axioms RelativeConicArcs.AMELU.diagonalDuality_existsUnique_unit_smul_eq
#print axioms RelativeConicArcs.AMELU.diagonalDuality_multiplier_ratio_eq
#print axioms RelativeConicArcs.AMELU.diagonalMultiplierSpace_finrank_le_one
#print axioms RelativeConicArcs.AMELU.diagonalMultiplierSpace_self_eq_span_one
#print axioms RelativeConicArcs.AMELU.diagonalMultiplier_ne_zero_at
#print axioms RelativeConicArcs.AMELU.diagonallyIsodual_fixedPartyProjectiveTransversal_dichotomy
#print axioms RelativeConicArcs.AMELU.encoderConversion_inverseTranspose_and_physical_isClifford
#print axioms RelativeConicArcs.AMELU.encoderConversion_inverseTranspose_chosenLeg
#print axioms RelativeConicArcs.AMELU.encoderConversion_logical_and_physical_isClifford
#print axioms RelativeConicArcs.AMELU.equalPhaseState_hasMinimalComputationalSupport
#print axioms RelativeConicArcs.AMELU.existsUnique_arcSyndrome_supported_on_three
#print axioms RelativeConicArcs.AMELU.existsUnique_arcSyndrome_weight_three_on_support
#print axioms RelativeConicArcs.AMELU.exists_pauliLabel_pairing_eq_dual
#print axioms RelativeConicArcs.AMELU.fixedPartyKernel_eq_specialLinear_or_splitTorus
#print axioms RelativeConicArcs.AMELU.fixedPartyProjectiveTransversal_eq_affineSpecialLinear_or_splitTorus
#print axioms RelativeConicArcs.AMELU.genericCSSLabel_lowerDualityShear
#print axioms RelativeConicArcs.AMELU.genericCSSLabel_upperDualityShear
#print axioms RelativeConicArcs.AMELU.genericDiagonalDualityOfMultiplier
#print axioms RelativeConicArcs.AMELU.genericLocallyUnitaryEquivalent_equalPhaseState_implies_genericLocallyCliffordEquivalent
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationExtension_splits_iff
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationFactorSet_associativity
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationFactorSet_change
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationFactorSet_trivializable_iff_splits
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationGroupExtensionSplitting
#print axioms RelativeConicArcs.AMELU.genericPartyPermutationSemidirectProductEquiv
#print axioms RelativeConicArcs.AMELU.genericPartyPermutation_natCard
#print axioms RelativeConicArcs.AMELU.grs_projectiveTransversal_eq_affineSpecialLinear
#print axioms RelativeConicArcs.AMELU.isAME_equalPhaseState_arcKernel
#print axioms RelativeConicArcs.AMELU.isAME_equalPhaseState_iff_isMDSCode634
#print axioms RelativeConicArcs.AMELU.isDiagonallyIsodual_iff_finrank_eq_one
#print axioms RelativeConicArcs.AMELU.isMDSCode2m_oneLegQuantumMDSParameters
#print axioms RelativeConicArcs.AMELU.isMDSCode634_arcKernel
#print axioms RelativeConicArcs.AMELU.locallyUnitaryEquivalent_admitted_nonGRS_pencil_iff_pencilZ_eq
#print axioms RelativeConicArcs.AMELU.locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent
#print axioms RelativeConicArcs.AMELU.locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent_from_generic
#print axioms RelativeConicArcs.AMELU.map_pencilA
#print axioms RelativeConicArcs.AMELU.map_pencilB
#print axioms RelativeConicArcs.AMELU.map_pencilGRSQuartic
#print axioms RelativeConicArcs.AMELU.map_pencilZ
#print axioms RelativeConicArcs.AMELU.mem_cssSupportedLabelSpace_iff_support_subset
#print axioms RelativeConicArcs.AMELU.negativeSignedCyclePolynomial_factor
#print axioms RelativeConicArcs.AMELU.not_isDiagonallyIsodual_iff_finrank_eq_zero
#print axioms RelativeConicArcs.AMELU.not_locallyUnitaryEquivalent_of_ten_vs_atMostSix_concurrences
#print axioms RelativeConicArcs.AMELU.offDiagonalBlock_fixedPartyProjectiveTransversal_eq_affineSpecialLinear
#print axioms RelativeConicArcs.AMELU.oneLegQuantumMDSParameters_singletonEquality
#print axioms RelativeConicArcs.AMELU.pauliSymplecticToDual_injective
#print axioms RelativeConicArcs.AMELU.pencilFrameRatio_crossDifference
#print axioms RelativeConicArcs.AMELU.pencilFrameRatio_eq_iff
#print axioms RelativeConicArcs.AMELU.pencilGalePairing_multiplier
#print axioms RelativeConicArcs.AMELU.pencilGalePairing_multiplier_zero_iff
#print axioms RelativeConicArcs.AMELU.pencilZ_eq_iff_samePencilYOrbit
#print axioms RelativeConicArcs.AMELU.positiveSignedCyclePolynomial_factor
#print axioms RelativeConicArcs.AMELU.projectivelyEquivalent_equalPhaseState_locallyCliffordEquivalent
#print axioms RelativeConicArcs.AMELU.q13_zFour_not_locallyUnitaryEquivalent_zTwelve
#print axioms RelativeConicArcs.AMELU.rankFourMultiplicity_eq_sixty_add_concurrency
#print axioms RelativeConicArcs.AMELU.reducedTransportDivisor_eq_zero_iff_axial_of_charSeven
#print axioms RelativeConicArcs.AMELU.reducedTransportDivisor_eq_zero_iff_three_factors
#print axioms RelativeConicArcs.AMELU.reducedTransportDivisor_eq_zero_iff_z
#print axioms RelativeConicArcs.AMELU.signedTransportFactor_sub_two_mul_axial
#print axioms RelativeConicArcs.AMELU.splitTorusWeylBlock_isSpecialLinear
#print axioms RelativeConicArcs.AMELU.splitTorusWeylBlock_mul_self
#print axioms RelativeConicArcs.AMELU.splitTorusWeylBlock_mul_splitTorusBlock
#print axioms RelativeConicArcs.AMELU.stateInnerProduct_translatedEqualPhaseState_eq_zero
#print axioms RelativeConicArcs.AMELU.supportedArcSyndrome_bijective_of_card_three
#print axioms RelativeConicArcs.AMELU.tensorWeylAction_X_equalPhaseState_eq_translated
#print axioms RelativeConicArcs.AMELU.tensorWeylAction_Z_translatedEqualPhaseState
#print axioms RelativeConicArcs.AMELU.tensorWeylAction_equalPhaseState_of_mem_cssLabelSpace
#print axioms RelativeConicArcs.AMELU.translatedEqualPhaseState_eq_iff
#print axioms RelativeConicArcs.AMELU.twistedPencilGaleDivisor_refl
#print axioms RelativeConicArcs.AMELU.twistedPencil_sectors_disjoint
